services:
  libertya:
    build:
      context: ./libertya
    ports:
      - 8080:8080
      - 8443:8443
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: libertya
      DB_NAME: libertya
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}